// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "开发人员",
            "url": "https://cas.luler.top/",
            "email": "1207032539@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/banIp": {
            "post": {
                "description": "封禁ip接口",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IP封禁相关接口"
                ],
                "summary": "封禁ip接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ip数据，多个用英文逗号隔开，格式:127.0.1,192.168.1.1",
                        "name": "ips",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "封禁协议,不传-全部协议，指定协议：tcp udp icmp",
                        "name": "protocol",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "封禁端口号,0-全端口（默认），1-65535（指定端口，传封禁协议时才有效）",
                        "name": "port",
                        "in": "formData"
                    },
                    {
                        "type": "integer",
                        "description": "过期时间，不传则无过期时间，格式：2006-01-02 15:04:05",
                        "name": "expiredAt",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "封禁原因",
                        "name": "reason",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "用户登录，获取访问授权",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "授权相关接口"
                ],
                "summary": "登录接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "接口文档",
	Description:      "当前页面用于展示项目一些开放的接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
